[env:cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified @ 0.2.20
    m5stack/M5UnitUnified @ 0.5.5
    m5stack/M5Unit-NFC @ 0.1.0
    bblanchon/ArduinoJson @ 7.4.3
    olikraus/U8g2 @ 2.36.18
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DFIRMWARE_VERSION=\"0.2.0\"
